### PR TITLE
Better highlighting of Perl 6 identifiers

### PR DESCRIPTION
**Pull request by azawawi**

### CODE REVIEW

**Comment by Fank** [comment]
@kevinsawicki looks good to me

**Comment by kevinsawicki** [comment]
@azawawi thanks for this :ship: 

@Fank thanks for taking a look :+1:

**Comment by azawawi** [comment]
Thanks :+1:

**Comment by infininight** [comment]
@azawawi Was synchronizing your recent changes to the Perl 6 grammar into TextMate and noticed an oddity in this PR. In 0319154f544aee3d46fb3e8f266ddccb48ca4120 you introduce a new match 'routine.name'. This appears to function to match every word not otherwise matched by the grammar, as it's not using a standard scope it won't be themed so does it have another purpose? Seems overkill to match every word, also since this match comes before 'support.function' it is preventing it from matching.

**Comment by azawawi** [comment]
@infininight Sorry for being late on this one. Perl 6 has a lot of keywords and operator words that can be used inside identifiers. Having a dash inside an identifier introduces such a thing. Please see https://github.com/azawawi/language-perl/commit/5098af0898224f4528dc3bc17fa1719b477f160d for test cases.

I remember [perl6.vim](https://github.com/vim-perl/vim-perl/blob/master/syntax/perl6.vim) having the same performance problem early in development.

If you have a more efficient method of doing it, please advise.

**Pull request merged**
