### PR TITLE
Fix format highlighting

### PR DESCRIPTION
**Pull request by Fank**
* Allow '_' in format variable
* Removed duplicate format entry

@kevinsawicki i don't have write permission on this repo :cry:

### CODE REVIEW

**Comment by 50Wliu** [comment]
@Fank Have you tried creating a new branch?  Generally there shouldn't be any direct pushes to master so that there can be some code review.

**Comment by Fank** [comment]
I tried to create a new brach but i can't push a commit to a new branch.

**Comment by Fank** [comment]
```
C:\Users\Fank\.atom\packages\language-perl [format +0 ~1 -0]> git push
ERROR: Permission to atom/language-perl.git denied to Fank.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
C:\Users\Fank\.atom\packages\language-perl [format +0 ~1 -0]>
```

**Comment by kevinsawicki** [comment]
> i don't have write permission on this repo :cry:

So sorry about this, I accidentally set the permission for the perl team to read instead of write, fixed now, thanks for letting me know.

**Comment by kevinsawicki** [comment]
Thanks!

**Pull request merged**
