### PR TITLE
Add firstLineMatch support for Emacs/Vim modelines

### PR DESCRIPTION
**Pull request by Alhadis**
Exactly as advertised. Allows Perl/Perl6 files with an Emacs or Vim modeline in the header to activate the grammar.

This is pretty much copy+pasta from atom/language-javascript#420, so if the accuracy of these expressions gets the green light from Atom staff, @50Wliu can go ahead and merge the other one too. =)

### CODE REVIEW

**Comment by Alhadis** [comment]
@Fank Hold on for a second, I've noticed an error with the hashbang-matching... I'm in the middle of fixing it, and adding tests to protect against regressions.

**Comment by Alhadis** [comment]
Basically, this will trigger the Perl grammar when it shouldn't:

```bash
#!/bin/env --type=perl
```

**Comment by Fank** [comment]
@Alhadis tell if your done

**Comment by Alhadis** [comment]
@Fank Okay, I've bulletproofed it. You can go ahead and review/merge now.

**Comment by Alhadis** [comment]
@Fank Just so you know, I've another (huge) pull request in the works for this grammar, and it'd be nice to get these two PRs merged first... =)

**Pull request merged**
