### PR TITLE
Update specs for first-mate changes

### PR DESCRIPTION
**Pull request by 50Wliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Newlines are no longer guaranteed to exist on first-mate@7.0.9+.  Don't try to match them and don't test for them in specs.

/cc @Fank

### CODE REVIEW

**Comment by 50Wliu** [comment]
:green_heart:

**Comment by 50Wliu** [comment]
And uh...I missed one by accident.  Forgot to re-test specs locally before pushing.  :see_no_evil:

**Comment by Alhadis** [comment]
> And uh...I missed one by accident. Forgot to re-test specs locally before pushing

Isn't there an emoji that says that too?

**Comment by 50Wliu** [comment]
I was actually on the Trusty branch which didn't have these changes :P.  Mixed things up, promptly realized, and deleted my comment.

**Comment by Alhadis** [comment]
Maybe we need a broken :green_heart: emoji for these situations. 😄

**Comment by 50Wliu** [comment]
:broken_heart: :(

**Pull request merged**
